package Game;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 * @author danie
 */

public class GameOver extends javax.swing.JFrame {

    // Creates new form GameOver
    public GameOver(Home home, Highscores scorePanel, int score) {
        initComponents();
        setBounds(300,300,600,434);
        setLocationRelativeTo(null);
        this.score = score;
        this.home = home;
        this.scorePanel = scorePanel;
        updateScore(this.score);
        updateMessage();
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Exit");
          getRootPane().getActionMap().put("Exit", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  System.exit(0);
              }
       });
       getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"), "Credits");
          getRootPane().getActionMap().put("Credits", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  JOptionPane.showMessageDialog(getRootPane(), "CS2450 Swing Project\n"
                                                             + "Spring 2021\n"
                                                             + "Arsh Chaudhry  #014897038\n"
                                                             + "Yuqing Han        #011964602\n"
                                                             + "Danielle Yap      #3014946308\n"
                                                             + "Chengzhi Zhao  #014347567");
              }
       });
    }

    // recieves score and updates screen text
    public void updateScore(int num) {
        score = num;
        scoreUpdate.setText("" + num);
    }
    
    public void updateMessage(){
        int[] temp = scorePanel.highestScore();
        int i = 0;
        if(temp.length != 0){
            message.setText("Nice try");
            getContentPane().repaint();
            userInput.setEnabled(false);
            saveScore.setEnabled(false);
            while(i < temp.length){
                if(score > temp[i] && score != temp[i]){
                    message.setText("Your score is higher than " + (i+1) + "th player, do you want to save your score?");
                    getContentPane().repaint();
                    userInput.setEnabled(true);
                    saveScore.setEnabled(true);
                    break;
                }
                i++; 
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        scoreUpdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();
        saveScore = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        scoreUpdate.setFont(new java.awt.Font("Bauhaus 93", 2, 36)); // NOI18N
        scoreUpdate.setForeground(new java.awt.Color(51, 102, 255));
        scoreUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scoreUpdate.setText("000");
        scoreUpdate.setMaximumSize(new java.awt.Dimension(601, 401));
        getContentPane().add(scoreUpdate);
        scoreUpdate.setBounds(345, 125, 131, 40);

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GAME OVER");
        jLabel2.setMaximumSize(new java.awt.Dimension(601, 401));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 580, 105);

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("SCORE:");
        jLabel3.setMaximumSize(new java.awt.Dimension(601, 401));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(179, 125, 160, 40);

        endButton.setBackground(new java.awt.Color(51, 102, 255));
        endButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        endButton.setText("END");
        endButton.setToolTipText("Return to the home screen");
        endButton.setBorderPainted(false);
        endButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        endButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });
        getContentPane().add(endButton);
        endButton.setBounds(241, 342, 125, 45);

        saveScore.setBackground(new java.awt.Color(51, 102, 255));
        saveScore.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        saveScore.setText("Save");
        saveScore.setToolTipText("Save your score to the highscore board");
        saveScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScoreActionPerformed(evt);
            }
        });
        getContentPane().add(saveScore);
        saveScore.setBounds(241, 297, 125, 45);

        message.setFont(new java.awt.Font("Bauhaus 93", 2, 18)); // NOI18N
        message.setForeground(new java.awt.Color(51, 102, 255));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(message);
        message.setBounds(10, 190, 580, 51);

        userInput.setToolTipText("Enter your initials ");
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });
        getContentPane().add(userInput);
        userInput.setBounds(217, 252, 167, 34);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Player:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(121, 252, 92, 34);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // returns to home when pressed
    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        try {
            scorePanel.readFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GameOver.class.getName()).log(Level.SEVERE, null, ex);
        }
        scorePanel.updateScore();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_endButtonActionPerformed

    private void saveScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScoreActionPerformed
            // TODO add your handling code here:
        try{
            File file =new File("score.txt");    

        //if file doesnt exists, then create it    
        if(!file.exists()){    
            file.createNewFile();   
        }

        //true = append file    
            FileWriter fileWritter = new FileWriter(file,true);        
            BufferedWriter bufferWritter = new BufferedWriter(fileWritter);
            bufferWritter.write("\n" + userInput.getText() + "," + score + ",");
            bufferWritter.close();
            fileWritter.close();   
            saveScore.setEnabled(false);

        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_saveScoreActionPerformed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_userInputActionPerformed

    private Home home;
    private Highscores scorePanel;
    private int score;
    private String userName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel message;
    private javax.swing.JButton saveScore;
    public javax.swing.JLabel scoreUpdate;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
