/*
 * edited by ChengZhi Zhao
 */
package Game;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 * @author Arsh
 */

public class Highscores extends javax.swing.JFrame {

    /**
     * @param home
     */
    public Highscores(Home home) throws FileNotFoundException {
        initComponents();
        setBounds(300,300,600,434);
        setLocationRelativeTo(null);
        readFile();
        updateScore();
        this.home = home;
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Exit");
          getRootPane().getActionMap().put("Exit", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  System.exit(0);
              }
       });
       getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"), "Credits");
          getRootPane().getActionMap().put("Credits", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  JOptionPane.showMessageDialog(getRootPane(), "CS2450 Swing Project\n"
                                                             + "Spring 2021\n"
                                                             + "Arsh Chaudhry  #014897038\n"
                                                             + "Yuqing Han        #011964602\n"
                                                             + "Danielle Yap      #3014946308\n"
                                                             + "Chengzhi Zhao  #014347567");
              }
       });
    }
    
    /**
     * read the file and sort the data and display on the score panel
     * @throws FileNotFoundException 
     */
    public void readFile() throws FileNotFoundException{
        File scoreFile = new File("score.txt");
        Scanner inputFile;
        List<String> temp = new ArrayList<String>();
        
        if(!scoreFile.exists()){
            throw new FileNotFoundException("Not exist");//if this file does not exist, then throw a exception.
        }
        else{
             inputFile = new Scanner(scoreFile);
             while(inputFile.hasNext() ){
                 temp.add(inputFile.next());
             }
        }
        
        Collections.sort(temp, new FileComparator());//sorting the ArrayList
        
        inputFile.close();
        
        values = temp;
        
    }
    
    public void updateScore(){
        String[] temp;
        String[] temp1;
        int k = 0;
        int i =0;
        
        temp = values.toArray(new String[values.size()]);
        
        if(temp.length > 0){
          while(i < temp.length && i < 4){
              temp1 = temp[i].split(",");
              grouping.get(i).setText("" + temp1[k] + "...." + temp1[k+1]);
              i++;
            }  
        }
            
    }
    
    public int[] highestScore(){
        String[] temp;
        String[] temp1;
        int[] topFour = new int[4];
        int i =0;
        
        temp = values.toArray(new String[values.size()]);
        
        if(temp.length > 0){
          while(i < temp.length && i < 4){
              temp1 = temp[i].split(",");
              topFour[i] = parseInt(temp1[1]);
              i++;
            }  
        }
        
        return topFour;
    }
    
    class FileComparator implements Comparator<String>{

        @Override
        public int compare(String o1, String o2) {
            String array1[] = o1.split(",");
            String array2[] = o2.split(",");
            if(parseInt(array1[1]) == parseInt(array2[1])) {
                return 0;
            }
            if(parseInt(array1[1]) < parseInt(array2[1])){
                return 1;
            }
            return -1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highscoresTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        fourth = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        third = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        highscoresTitle.setFont(new java.awt.Font("Bauhaus 93", 2, 58)); // NOI18N
        highscoresTitle.setForeground(new java.awt.Color(51, 102, 255));
        highscoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoresTitle.setText("HIGHSCORES");
        highscoresTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(highscoresTitle);
        highscoresTitle.setBounds(0, 40, 600, 80);

        backButton.setBackground(new java.awt.Color(51, 102, 255));
        backButton.setFont(new java.awt.Font("Bauhaus 93", 2, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.setToolTipText("Return to the home screen");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 370, 50, 21);

        fourth.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        fourth.setForeground(new java.awt.Color(51, 102, 255));
        fourth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourth.setText("ABC.....0000");
        getContentPane().add(fourth);
        fourth.setBounds(170, 250, 260, 40);
        grouping.add(first);
        grouping.add(second);
        grouping.add(third);
        grouping.add(fourth);

        first.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        first.setForeground(new java.awt.Color(51, 102, 255));
        first.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        first.setText("ABC.....0000");
        getContentPane().add(first);
        first.setBounds(170, 130, 260, 40);

        third.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        third.setForeground(new java.awt.Color(51, 102, 255));
        third.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        third.setText("ABC.....0000");
        getContentPane().add(third);
        third.setBounds(170, 210, 260, 40);

        second.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        second.setForeground(new java.awt.Color(51, 102, 255));
        second.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        second.setText("ABC.....0000");
        getContentPane().add(second);
        second.setBounds(170, 170, 260, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //added some variable
    private Home home;
    private List<JLabel> grouping = new ArrayList<JLabel>();
    private List<String> values;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel first;
    private javax.swing.JLabel fourth;
    private javax.swing.JLabel highscoresTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel second;
    private javax.swing.JLabel third;
    // End of variables declaration//GEN-END:variables
}
