package Game;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 * @author Arsh
 */
public class Home extends javax.swing.JFrame {

     // Creates new form Home  
    public Home() throws FileNotFoundException {
        initComponents();
        setBounds(300,300,600,434);
        setLocationRelativeTo(null);
        scorePanel = new Highscores(this);   
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Exit");
          getRootPane().getActionMap().put("Exit", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  System.exit(0);
              }
       });
       getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"), "Credits");
          getRootPane().getActionMap().put("Credits", new AbstractAction() { 
              public void actionPerformed(ActionEvent e) {
                  JOptionPane.showMessageDialog(getRootPane(), "CS2450 Swing Project\n"
                                                             + "Spring 2021\n"
                                                             + "Arsh Chaudhry  #014897038\n"
                                                             + "Yuqing Han        #011964602\n"
                                                             + "Danielle Yap      #3014946308\n"
                                                             + "Chengzhi Zhao  #014347567");
              }
       });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        highscoreButton = new javax.swing.JButton();
        creditButton = new javax.swing.JButton();
        pongButton = new javax.swing.JButton();
        symbol = new javax.swing.JLabel();
        whiteEyeBackGround = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        playButton.setBackground(new java.awt.Color(51, 102, 255));
        playButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        playButton.setText("PLAY");
        playButton.setToolTipText("Begin the game");
        playButton.setBorder(null);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(410, 220, 170, 50);

        highscoreButton.setBackground(new java.awt.Color(51, 102, 255));
        highscoreButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        highscoreButton.setText("HIGHSCORES");
        highscoreButton.setToolTipText("Display highscores");
        highscoreButton.setBorder(null);
        highscoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(highscoreButton);
        highscoreButton.setBounds(410, 280, 170, 50);

        creditButton.setBackground(new java.awt.Color(51, 102, 255));
        creditButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        creditButton.setText("CREDITS");
        creditButton.setToolTipText("Display the game creators");
        creditButton.setBorder(null);
        creditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creditButton);
        creditButton.setBounds(410, 340, 170, 50);

        pongButton.setBackground(new java.awt.Color(51, 102, 255));
        pongButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        pongButton.setText("PONG");
        pongButton.setToolTipText("Begin game of Pong");
        pongButton.setBorder(null);
        pongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pongButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pongButton);
        pongButton.setBounds(410, 160, 170, 50);

        symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/output-onlinepngtools (1).png"))); // NOI18N
        getContentPane().add(symbol);
        symbol.setBounds(110, 70, 180, 220);
        getContentPane().add(whiteEyeBackGround);
        whiteEyeBackGround.setBounds(90, 110, 60, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/676549.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 160, 80, 30);
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 600, 400);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // goes to gameplay screen
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        playPanel = new Play(this, scorePanel);
        playPanel.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_playButtonActionPerformed

    // goes to high score screen
    private void highscoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreButtonActionPerformed
        scorePanel.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_highscoreButtonActionPerformed

    // goes to credits screen
    private void creditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditButtonActionPerformed
        creditPanel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_creditButtonActionPerformed

    private void pongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pongButtonActionPerformed
        new Pong().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pongButtonActionPerformed
    
    private final Credits creditPanel = new Credits(this);
    private Highscores scorePanel;
    private Play playPanel;
    private Pong pongPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton creditButton;
    private javax.swing.JButton highscoreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton pongButton;
    private javax.swing.JLabel symbol;
    private javax.swing.JLabel whiteEyeBackGround;
    // End of variables declaration//GEN-END:variables
}
